---
title: "R objects Workflow and functions"
author: "Melanie Beebe"
format: html
editor: visual
---

## create a vector

```{r}
set.seed(12)
my_unif <- runif(30)
is.vector(my_unif)
```

## subset the vector

```{r}
my_unif[1:10]
#create indexing vector
my_unif[c(1:3, 15:17)]
```

## sort the vector

```{r}
#sort (from smallest to largest)
sort(my_unif)
```

## create a vector with strings in it

```{r}
#create and sort character vector (sorts alphabetically and then by number)
char_vec <- c("da1", "ad1", "c2", "Ce1")
sort(char_vec)
```

```{r}
#sequences
seq(1, 10, 2)
seq(1:10)
1:10*2
1:15/2
```

```{r}
my_iris <- as.matrix(iris[, 1:4])
str(iris)
attributes(my_iris)
dim(my_iris)
```

# Vectors

## data frame

```{r}
iris
str(iris)
attributes(iris)
iris[1:4, 2:4] 
iris[1, ]
iris[1,, drop = FALSE]
`[`(iris, 1, , drop = FALSE)
```

```{r}
data(trees)
trees
class(trees)
str(trees)
```

```{r}
trees$Height
```

##get attributes from the data frame

```{r}
attributes(trees)
```

```{r}
names(trees)
#or
colnames(trees)
```

above output is a character vector

```{r}
class(colnames(trees))
```

```{r}
#subset column names
colnames(trees[2:3])
```

## lists

```{r}
my_df <- data.frame(number = 1:5, letter = c("a", "b", "c", "d", "e"))
my_df
my_list <- list(my_df, rnorm(4), c("!", "?"))
my_list

```

```{r}
my_list <- list(my_data_frame = my_df, normVals = rnorm(4), punctuation = c("!", "?"))
my_list
str(my_list)
```

```{r}
attributes(my_list)
```

Looking at trees data again

```{r}
is.list(trees)
is.data.frame(trees)
```
```{r}
trees[1]
trees[[1]]      #simplified to a vector
```
## look at linear model fit

```{r}
fit <- lm(Volume ~ Height + Girth, data = trees)
```

## look at structure but restrict info:

```{r}
str(fit, max.level = 1)        #shows first level of structure
```

### some helper functions exist

```{r}
fit$coefficients
#alt
coef(fit)         #helper function
fit$residuals
residuals(fit)
```

